title: Elizabeth Contreras
logo: images/cali.png
description: I am a political scientist by training but have always had a close connection with the world of data throughout my career in public management. Although I started working in 2015, it was in 2019 that I shifted my career towards user experience research for the design and innovation of digital platforms. I enjoy working with products that innovate and improve people’s quality of life and whose growth is based on evidence and active listening to their users.
description: Let´s connect! e.contrerasmarin@gmail.com




remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
